### ISSUE TITLE
FieldProvider calls undefined Raven_Client::getUser() method

### ISSUE THREAD

**Issue by tzurbaev** [understand/understand-laravel5#26]
Seems that current version of `understand-laravel5` is incompatible with the `sentry/sentry-laravel` package: when both installed, understand's `FieldProvider` class attempts to call `\Sentry::getUser()` method (which is proxied down to `Raven_Client::getUser()` from Sentry's facade) that is actually does not exist.

This breaks logging at all, since any call to the Log's method (debug, error, etc.) produces this error.

Steps to reproduce:

```bash
laravel new test
cd test
composer require sentry/sentry-laravel understand/understand-laravel5
php artisan tinker
```
and then:

```
>>> Log::error('Test')

PHP Error:  Call to undefined method Raven_Client::getUser() in /projects/test/sentry-understand-error/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php on line 22
```

**Comment by aivis** [comment]
This is fixed in the version `2.0.6`. Thanks for your pull-request @tzurbaev !
