### ISSUE TITLE
How to disable understand depending on env config?

### ISSUE THREAD

**Issue by SturmDrangAltaar** [understand/understand-laravel5#6]
I want to be able to pass in a variable from my .env to disable/enable understand.io on different environments. For instance, I don't want to post to understand.io when working on localhost.

I can set 'enabled' on each log type in the config, but I'd prefer a global variable for enabled as well perhaps?

**Comment by aivis** [comment]
@SturmDrangAltaar at the moment there is no global variable which you can set to `false` (only each for each type of logs as you mentioned) but I think this is something what we should implement in the near future.

**Comment by LukasLt** [comment]
This could be solved by putting API key to .env
Setting no API key in env file would disable logging in preferred deployment
This would also allow to have different channels for separate deployments.

**Comment by aivis** [comment]
@LukasLt Yes, to use `env('UNDERSTAND_TOKEN');` for different environments is a good idea.
